# Generated by Django 4.0.5 on 2022-06-30 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataforstupact', '0002_mymodel_batch_mymodel_email_mymodel_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
