# Generated by Django 4.0.6 on 2022-07-08 13:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dataforstupact', '0009_alter_mymodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='stumartmodel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='stumart/products/')),
                ('price', models.IntegerField(default=0)),
                ('details', models.TextField(blank=True)),
                ('category', models.CharField(default='other', max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='batch',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='faculty',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
