# Generated by Django 4.0.6 on 2022-07-08 13:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dataforstupact', '0011_alter_stumartmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stumartmodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
