# Generated by Django 4.0.6 on 2022-07-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataforstupact', '0014_mymodel_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='seller',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
