# Generated by Django 4.0.6 on 2022-07-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataforstupact', '0015_orderlist_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='phonenumber',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
