# Generated by Django 4.0.6 on 2022-07-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataforstupact', '0016_orderlist_first_name_orderlist_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('notify', models.CharField(max_length=50)),
                ('status', models.CharField(default='unseen', max_length=8)),
            ],
        ),
    ]
