# Generated by Django 4.0.6 on 2022-07-10 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataforstupact', '0017_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='time',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
