# Generated by Django 4.0.6 on 2022-07-10 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataforstupact', '0018_notifications_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='time',
            field=models.CharField(default='10072022023458', max_length=20),
        ),
    ]
