# Generated by Django 4.0.6 on 2022-07-10 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataforstupact', '0019_alter_notifications_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='time',
            field=models.CharField(default='10072022030854', max_length=20),
        ),
    ]
