# Generated by Django 4.0.6 on 2022-07-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataforstupact', '0020_alter_notifications_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='notify',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='time',
            field=models.CharField(default='10072022040919', max_length=20),
        ),
    ]
