# Generated by Django 4.0.6 on 2022-07-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataforstupact', '0021_alter_notifications_notify_alter_notifications_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(max_length=30)),
                ('seller', models.CharField(blank=True, max_length=30)),
                ('region', models.CharField(max_length=40)),
                ('product', models.CharField(blank=True, max_length=30)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('phonenumber', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='orderlist',
        ),
        migrations.AlterField(
            model_name='notifications',
            name='time',
            field=models.CharField(default='10072022041456', max_length=20),
        ),
    ]
