# Generated by Django 4.0.6 on 2022-07-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataforstupact', '0022_order_list_delete_orderlist_alter_notifications_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='time',
            field=models.CharField(default='20220711045156', max_length=20),
        ),
    ]
