# Generated by Django 4.0.6 on 2022-07-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataforstupact', '0024_order_list_delivery_charge_order_list_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_list',
            name='status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='time',
            field=models.CharField(default='20220711082804', max_length=20),
        ),
    ]
