# Generated by Django 4.0.6 on 2022-07-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataforstupact', '0025_order_list_status_alter_notifications_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_list',
            name='title',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='time',
            field=models.CharField(default='20220711114741', max_length=20),
        ),
    ]
