# Generated by Django 4.0.6 on 2022-07-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataforstupact', '0027_alter_notifications_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='time',
            field=models.CharField(default='20220711124035', max_length=20),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='product',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
