# Generated by Django 4.0.6 on 2022-07-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataforstupact', '0028_alter_notifications_time_alter_order_list_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='reward',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='time',
            field=models.CharField(default='20220713062538', max_length=20),
        ),
    ]
