# Generated by Django 4.0.6 on 2022-07-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataforstupact', '0029_mymodel_reward_alter_notifications_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='image',
            field=models.ImageField(default='user.svg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
