# Generated by Django 4.0.6 on 2022-07-18 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dataforstupact', '0030_alter_mymodel_image_alter_notifications_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='stumartmodel',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
