# Generated by Django 4.0.6 on 2022-07-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataforstupact', '0031_stumartmodel_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='verified',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
