# Generated by Django 4.0.6 on 2022-07-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataforstupact', '0032_mymodel_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='verifyrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('filevalue', models.FileField(upload_to='verify/')),
            ],
        ),
    ]
