# Generated by Django 4.0.6 on 2022-08-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataforstupact', '0033_verifyrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='stumartmodel',
            name='verify',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
