# Generated by Django 4.0.6 on 2022-08-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataforstupact', '0034_stumartmodel_verify'),
    ]

    operations = [
        migrations.CreateModel(
            name='queries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('subject', models.CharField(choices=[('User Experience', 'User Experience'), ('Bad Service', 'Bad Service'), ('Scam', 'Scam'), ('Feedbacks', 'Feedbacks'), ('Other', 'Other')], default='User Experience', max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='image',
            field=models.ImageField(default='user.png', upload_to=''),
        ),
    ]
