# Generated by Django 4.0.6 on 2022-08-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataforstupact', '0035_queries_alter_mymodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='queries',
            name='email',
            field=models.EmailField(blank=True, max_length=30),
        ),
    ]
