# Generated by Django 4.0.6 on 2022-08-13 16:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dataforstupact', '0038_queries_msgid_alter_queries_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queries',
            name='msgid',
        ),
        migrations.AlterField(
            model_name='queries',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
